---
apiVersion: v1
kind: Pod
metadata:
  name: pull-secrets
spec:
  restartPolicy: Never
  runtimeClassName: kata-cc
  imagePullSecrets:
    - name: acr-secret
  containers:
    - name: dmihai-redis
      image: "dmihaiacr.azurecr.io/redis:6.0.8"
      imagePullPolicy: Always
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      ports:
        - containerPort: 6379
          name: redis
