name: Kata Containers CI
on:
  pull_request_review:
    types: [submitted]

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      has_test_gha: ${{ steps.test-gha.outputs.is_present }}
    steps:
      - name: Check for /test-gha
        id: test-gha
        run: |
          comment_body=$(
          cat <<'END_COMMENT'
          ${{ github.event.review.body }}
          END_COMMENT
          )
          if echo "$comment_body" | sed 's/\r$//' | grep -xq '^/test-gha$'; then
            echo "is_present=true" >> $GITHUB_OUTPUT
          fi
      
  # NOTE: Ensure we only rerun failed jobs.
  # NOTE: Ensure we're not retesting the same commit.
  
  # Get workflow ID from run ID:
  # gh api repos/sprt/kata-containers/actions/runs/6344599635 | jq -r '.workflow_id'
  # Get workflow ID from yaml:
  # gh api repos/sprt/kata-containers/actions/workflows | jq -r --arg file ".github/workflows/ci-on-comment.yaml" '.workflows[] | select(.path == $file) | .id'
  # All runs for workflow ID:
  # gh api repos/sprt/kata-containers/actions/workflows/70949260/runs

  # Get commit hash corresponding to comment
  # Check if ci.yaml run exists with above commit hash input
  #   If yes:
  #     If still running: do nothing
  #     Else: rerun only failed
  #   Else: dispatch event

  kata-containers-ci-on-comment:
    needs: metadata
    if: |
      contains(fromJSON('["MEMBER", "OWNER"]'), github.event.review.author_association) &&
      (github.event.pull_request.base.ref == 'main' ||
        startsWith(github.event.pull_request.base.ref, 'stable-')) &&
      needs.metadata.outputs.has_test_gha == 'true'
    uses: ./.github/workflows/ci.yaml
    with:
      caller-workflow: ${{ github.workflow }}
      commit-hash: ${{ github.sha }}
      pr-number: ${{ github.event.pull_request.number }}
      tag: ${{ github.event.pull_request.number }}-${{ github.sha }}
    secrets: inherit
